*Note: This manuscript is not meant to be an explanation of all Fundamental Analysis. It just shows some codes that you may use to explore YFinance stocks.

For more detailed description, check with bard.google.com



---

#Install and Import YFinance

In [29]:
!pip install --upgrade yfinance
import yfinance as yf

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.27)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.23.5)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2022.7.1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.3.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2023.7.22)



---

#Stock.Info

In [30]:
stock = yf.Ticker("D05.SI")

In [31]:
import pandas as pd

info = stock.info

df1 = pd.DataFrame(info.items(), columns=["Key", "Value"])

display(df1)

                   Key                        Value
0             address1  Marina Bay Financial Centre
1             address2  Tower 3 12 Marina Boulevard
2                 city                    Singapore
3                  zip                       018982
4              country                    Singapore
..                 ...                          ...
111       grossMargins                          0.0
112      ebitdaMargins                          0.0
113   operatingMargins                      0.58947
114  financialCurrency                          SGD
115   trailingPegRatio                       1.5165

[116 rows x 2 columns]



---

#Stock.Actions (Dividends and Splits)

In [41]:
# get historical market data
hist = stock.history(period="max")

# show actions (dividends, splits)
display(stock.actions)

                           Dividends  Stock Splits
Date
2000-05-17 00:00:00+08:00       0.16           0.0
2000-08-08 00:00:00+08:00       0.14           0.0
2001-05-16 00:00:00+08:00       0.15           0.0
2001-08-02 00:00:00+08:00       0.14           0.0
2002-05-03 00:00:00+08:00       0.16           0.0
...                              ...           ...
2022-05-11 00:00:00+08:00       0.36           0.0
2022-08-15 00:00:00+08:00       0.36           0.0
2022-11-11 00:00:00+08:00       0.36           0.0
2023-04-10 00:00:00+08:00       0.50           0.0
2023-05-09 00:00:00+08:00       0.42           0.0

[66 rows x 2 columns]



---

#Stock.Financials

In [33]:
# show financials
display(stock.financials)

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,379876.358985,2126092.544987,912071.535022,152182.513517
Tax Rate For Calcs,0.126625,0.125064,0.114009,0.152183
Total Unusual Items,3000000.0,17000000.0,8000000.0,1000000.0
Total Unusual Items Excluding Goodwill,3000000.0,17000000.0,8000000.0,1000000.0
Net Income From Continuing Operation Net Minority Interest,8193000000.0,6805000000.0,4721000000.0,6391000000.0
Reconciled Depreciation,701000000.0,669000000.0,648000000.0,609000000.0
Net Interest Income,10941000000.0,8440000000.0,9076000000.0,9625000000.0
Interest Expense,4986000000.0,1745000000.0,3132000000.0,5967000000.0
Interest Income,15927000000.0,10185000000.0,12208000000.0,15592000000.0
Normalized Income,8190379876.358985,6790126092.544987,4713912071.535022,6390152182.513517
Net Income From Continuing And Discontinued Operation,8193000000.0,6805000000.0,4721000000.0,6391000000.0
Diluted Average Shares,2572833000.0,2562334000.0,2543231000.0,2555616000.0
Basic Average Shares,2572833000.0,2562334000.0,2543231000.0,2555616000.0
Diluted EPS,3.15,2.61,1.81,2.46
Basic EPS,3.15,2.61,1.81,2.46
Diluted NI Availto Com Stockholders,8108000000.0,6696000000.0,4606000000.0,6299000000.0
Net Income Common Stockholders,8108000000.0,6696000000.0,4606000000.0,6299000000.0
Otherunder Preferred Stock Dividend,85000000.0,109000000.0,115000000.0,92000000.0
Net Income,8193000000.0,6805000000.0,4721000000.0,6391000000.0
Minority Interests,-1000000.0,-2000000.0,-35000000.0,-38000000.0
Net Income Including Noncontrolling Interests,8194000000.0,6807000000.0,4756000000.0,6429000000.0
Net Income Continuous Operations,8194000000.0,6807000000.0,4756000000.0,6429000000.0
Tax Provision,1188000000.0,973000000.0,612000000.0,1154000000.0
Pretax Income,9382000000.0,7780000000.0,5368000000.0,7583000000.0
Special Income Charges,3000000.0,17000000.0,8000000.0,1000000.0
Other Special Charges,-3000000.0,-17000000.0,-8000000.0,-1000000.0
Gain On Sale Of Security,115000000.0,387000000.0,963000000.0,334000000.0
Operating Expense,6992000000.0,6569000000.0,6158000000.0,6258000000.0
Other Operating Expenses,2220000000.0,2278000000.0,2156000000.0,2292000000.0
Selling General And Administration,NaN,NaN,1093000000.0,1062000000.0
General And Administrative Expense,NaN,NaN,1093000000.0,1062000000.0
Rent And Landing Fees,396000000.0,416000000.0,452000000.0,452000000.0
Total Revenue,16494000000.0,14171000000.0,14584000000.0,14543000000.0
Operating Revenue,16494000000.0,14171000000.0,14584000000.0,14543000000.0

## Stock.Quarterly Financials

In [34]:
#show quarterly financials
display(stock.quarterly_financials)

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.4,0.4,0.4,0.4,0.4
Net Income From Continuing Operation Net Minority Interest,2629000000.0,2571000000.0,2341000000.0,2236000000.0,1815000000.0
Net Interest Income,3433000000.0,3271000000.0,3280000000.0,3020000000.0,2454000000.0
Interest Income,9957000000.0,3271000000.0,8266000000.0,3020000000.0,3591000000.0
Normalized Income,2629000000.0,2571000000.0,2341000000.0,2236000000.0,1815000000.0
Net Income From Continuing And Discontinued Operation,2629000000.0,2571000000.0,2341000000.0,2236000000.0,1815000000.0
Diluted Average Shares,NaN,2578834405.0,NaN,2573601565.0,NaN
Basic Average Shares,NaN,2578834405.0,NaN,2573601565.0,NaN
Diluted EPS,NaN,4.02,NaN,0.868821,NaN
Basic EPS,NaN,4.02,NaN,0.868821,NaN
Diluted NI Availto Com Stockholders,2629000000.0,2571000000.0,2256000000.0,2236000000.0,1815000000.0
Net Income Common Stockholders,2629000000.0,2571000000.0,2256000000.0,2236000000.0,1815000000.0
Net Income,2629000000.0,2571000000.0,2341000000.0,2236000000.0,1815000000.0
Net Income Including Noncontrolling Interests,2630000000.0,2571000000.0,2342000000.0,2236000000.0,1816000000.0
Net Income Continuous Operations,2630000000.0,2571000000.0,2342000000.0,2236000000.0,1816000000.0
Pretax Income,3011000000.0,2956000000.0,2705000000.0,2541000000.0,2088000000.0
Operating Expense,2004000000.0,1882000000.0,1865000000.0,1825000000.0,1658000000.0
Other Operating Expenses,-435000000.0,1882000000.0,-2907000000.0,1825000000.0,-589000000.0
Total Revenue,5045000000.0,4936000000.0,4411000000.0,4544000000.0,3792000000.0
Operating Revenue,5045000000.0,4936000000.0,4411000000.0,4544000000.0,3792000000.0



---

#Stock.Major Holders

In [35]:
# show major holders
display(stock.major_holders)

        0                                      1
0   0.96%        % of Shares Held by All Insider
1  55.94%       % of Shares Held by Institutions
2  56.49%        % of Float Held by Institutions
3     558  Number of Institutions Holding Shares

##Stock.Institutional Holders

In [36]:
# show institutional holders
display(stock.institutional_holders)

,Holder,Shares,Date Reported,% Out,Value
0,"Aristotle Capital Management, LLC",2953172,2023-03-31,0.0011,101293797
1,"Paradigm Asset Management Company, LLC",102400,2023-03-31,0.0000,3512319
2,"Pacer Advisors, Inc.",15030,2023-06-30,0.0000,515528



---

#Stock.Balance Sheet

In [37]:
# show balance sheet
display(stock.balance_sheet)

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Treasury Shares Number,15454520.0,20873000.0,25874000.0,10331000.0
Ordinary Shares Number,2572163480.0,2566745000.0,2549990000.0,2553605000.0
Share Issued,2587618000.0,2587618000.0,2575864000.0,2563936000.0
Total Debt,47079000000.0,53863000000.0,45213000000.0,57842000000.0
Tangible Book Value,51547000000.0,52164000000.0,49303000000.0,45811000000.0
Invested Capital,102577000000.0,109867000000.0,98135000000.0,107085000000.0
Net Tangible Assets,51547000000.0,52164000000.0,49303000000.0,45811000000.0
Common Stock Equity,56887000000.0,57526000000.0,54626000000.0,50981000000.0
Total Capitalization,102577000000.0,109867000000.0,98135000000.0,107085000000.0
Total Equity Gross Minority Interest,57072000000.0,57714000000.0,54643000000.0,51799000000.0
Minority Interest,185000000.0,188000000.0,17000000.0,818000000.0
Stockholders Equity,56887000000.0,57526000000.0,54626000000.0,50981000000.0
Other Equity Interest,2392000000.0,2392000000.0,3401000000.0,2009000000.0
Treasury Stock,331000000.0,443000000.0,542000000.0,257000000.0
Capital Stock,11826000000.0,11826000000.0,11484000000.0,11205000000.0
Common Stock,11826000000.0,11826000000.0,11484000000.0,11205000000.0
Total Liabilities Net Minority Interest,686296000000.0,628359000000.0,595295000000.0,527147000000.0
Derivative Product Liabilities,45265000000.0,20318000000.0,32904000000.0,17512000000.0
Long Term Debt And Capital Lease Obligation,47079000000.0,53863000000.0,45213000000.0,57842000000.0
Payables,14539000000.0,12074000000.0,15349000000.0,15193000000.0
Other Payable,11914000000.0,10459000000.0,13726000000.0,12880000000.0
Total Tax Payable,1061000000.0,964000000.0,740000000.0,1142000000.0
Accounts Payable,1564000000.0,651000000.0,883000000.0,1171000000.0
Total Assets,743368000000.0,686073000000.0,649938000000.0,578946000000.0
Investments And Advances,187667000000.0,144807000000.0,149126000000.0,131545000000.0
Investmentin Financial Assets,185387000000.0,142635000000.0,148264000000.0,130710000000.0
Available For Sale Securities,75457000000.0,69692000000.0,NaN,63746000000.0
Long Term Equity Investment,2280000000.0,2172000000.0,862000000.0,835000000.0
Investmentsin Associatesat Cost,2280000000.0,2172000000.0,862000000.0,835000000.0
Investmentsin Subsidiariesat Cost,0.0,0.0,0.0,0.0
Investment Properties,39000000.0,40000000.0,45000000.0,34000000.0
Goodwill And Other Intangible Assets,5340000000.0,5362000000.0,5323000000.0,5170000000.0
Net PPE,3199000000.0,3222000000.0,3293000000.0,3191000000.0
Accumulated Depreciation,NaN,NaN,-2181000000.0,-1976000000.0
Gross PPE,3199000000.0,3222000000.0,5474000000.0,5167000000.0
Other Properties,465000000.0,496000000.0,1512000000.0,1291000000.0
Machinery Furniture Equipment,1181000000.0,1042000000.0,1837000000.0,1716000000.0
Properties,1553000000.0,1684000000.0,2125000000.0,2160000000.0
Prepaid Assets,711000000.0,584000000.0,643000000.0,532000000.0
Receivables,10504000000.0,11502000000.0,12557000000.0,11239000000.0
Cash And Cash Equivalents,114301000000.0,107754000000.0,101485000000.0,65698000000.0
Cash Financial,2520000000.0,2140000000.0,2411000000.0,2303000000.0

##Stock.Quarterly Balance Sheet

In [38]:
display(stock.quarterly_balance_sheet)

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Treasury Shares Number,8597816.0,8783220.0,15454520.0,NaN,14115246.0
Ordinary Shares Number,2579019809.0,2578834405.0,2572163480.0,2573601565.0,2573502379.0
Share Issued,2587617625.0,2587617625.0,2587618000.0,2573601565.0,2587617625.0
Total Debt,49671000000.0,NaN,47079000000.0,NaN,52014000000.0
Tangible Book Value,53404000000.0,57595000000.0,51547000000.0,55556000000.0,50519000000.0
Invested Capital,108419000000.0,NaN,102577000000.0,NaN,107889000000.0
Net Tangible Assets,53404000000.0,57595000000.0,51547000000.0,55556000000.0,50519000000.0
Common Stock Equity,58748000000.0,57595000000.0,56887000000.0,55556000000.0,55875000000.0
Total Capitalization,108419000000.0,NaN,102577000000.0,NaN,107889000000.0
Total Equity Gross Minority Interest,58935000000.0,NaN,57072000000.0,NaN,56066000000.0
Minority Interest,187000000.0,NaN,185000000.0,NaN,191000000.0
Stockholders Equity,58748000000.0,57595000000.0,56887000000.0,55556000000.0,55875000000.0
Other Equity Interest,2392000000.0,NaN,2392000000.0,NaN,2392000000.0
Treasury Stock,NaN,NaN,331000000.0,NaN,NaN
Capital Stock,11612000000.0,NaN,11826000000.0,NaN,11500000000.0
Common Stock,11612000000.0,NaN,11826000000.0,NaN,11500000000.0
Total Liabilities Net Minority Interest,698972000000.0,687184000000.0,686296000000.0,710891000000.0,689571000000.0
Derivative Product Liabilities,51622000000.0,NaN,45265000000.0,NaN,38759000000.0
Long Term Debt And Capital Lease Obligation,49671000000.0,NaN,47079000000.0,NaN,52014000000.0
Payables,NaN,NaN,14539000000.0,NaN,NaN
Other Payable,NaN,NaN,11914000000.0,NaN,NaN
Total Tax Payable,NaN,NaN,1061000000.0,NaN,NaN
Accounts Payable,NaN,NaN,1564000000.0,NaN,NaN
Total Assets,757907000000.0,744968000000.0,743368000000.0,766637000000.0,745637000000.0
Investments And Advances,204724000000.0,NaN,187667000000.0,NaN,177702000000.0
Investmentin Financial Assets,202371000000.0,NaN,185387000000.0,NaN,175467000000.0
Available For Sale Securities,80223000000.0,NaN,NaN,NaN,71251000000.0
Long Term Equity Investment,2353000000.0,NaN,2280000000.0,NaN,2235000000.0
Investmentsin Associatesat Cost,2353000000.0,NaN,2280000000.0,NaN,2235000000.0
Investmentsin Subsidiariesat Cost,0.0,NaN,0.0,NaN,0.0
Investment Properties,NaN,NaN,39000000.0,NaN,NaN
Goodwill And Other Intangible Assets,5344000000.0,NaN,5340000000.0,NaN,5356000000.0
Net PPE,3215000000.0,NaN,3199000000.0,NaN,3173000000.0
Gross PPE,NaN,NaN,3199000000.0,NaN,NaN
Other Properties,NaN,NaN,465000000.0,NaN,NaN
Machinery Furniture Equipment,NaN,NaN,1181000000.0,NaN,NaN
Properties,NaN,NaN,1553000000.0,NaN,NaN
Prepaid Assets,NaN,NaN,711000000.0,NaN,NaN
Receivables,NaN,NaN,10504000000.0,NaN,NaN
Cash And Cash Equivalents,110076000000.0,NaN,114301000000.0,NaN,109959000000.0
Cash Financial,43294000000.0,NaN,2520000000.0,NaN,57928000000.0



---

#Stock.Cashflow

In [39]:
# show cashflow
display(stock.cashflow)

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,2100000000.0,7164000000.0,24334000000.0,10600000000.0
Repurchase Of Capital Stock,-11000000.0,-16000000.0,-1247000000.0,-114000000.0
Repayment Of Debt,0.0,-257000000.0,NaN,0.0
Issuance Of Debt,0.0,1000000000.0,NaN,0.0
Capital Expenditure,-669000000.0,-567000000.0,-547000000.0,-586000000.0
End Cash Position,43976000000.0,46690000000.0,42202000000.0,19935000000.0
Beginning Cash Position,46690000000.0,42202000000.0,19935000000.0,14221000000.0
Effect Of Exchange Rate Changes,-903000000.0,940000000.0,170000000.0,39000000.0
Changes In Cash,-1811000000.0,3548000000.0,22097000000.0,5675000000.0
Financing Cash Flow,-3886000000.0,-2582000000.0,-2369000000.0,-4964000000.0
Net Other Financing Charges,NaN,-853000000.0,1393000000.0,-805000000.0
Interest Paid Cff,-86000000.0,-64000000.0,-66000000.0,-76000000.0
Cash Dividends Paid,-3789000000.0,-2392000000.0,-2411000000.0,-3931000000.0
Common Stock Dividend Paid,-3789000000.0,-2392000000.0,-2411000000.0,-3931000000.0
Net Preferred Stock Issuance,NaN,0.0,-800000000.0,0.0
Preferred Stock Payments,NaN,0.0,-800000000.0,0.0
Net Common Stock Issuance,-11000000.0,-16000000.0,-447000000.0,-114000000.0
Common Stock Payments,-11000000.0,-16000000.0,-447000000.0,-114000000.0
Net Issuance Payments Of Debt,0.0,743000000.0,NaN,0.0
Net Long Term Debt Issuance,0.0,743000000.0,NaN,0.0
Long Term Debt Payments,0.0,-257000000.0,NaN,0.0
Long Term Debt Issuance,0.0,1000000000.0,NaN,0.0
Investing Cash Flow,-694000000.0,-1601000000.0,-415000000.0,-547000000.0
Net Other Investing Changes,NaN,NaN,NaN,-13000000.0
Dividends Received Cfi,86000000.0,42000000.0,31000000.0,29000000.0
Net Business Purchase And Sale,-114000000.0,-1098000000.0,93000000.0,21000000.0
Sale Of Business,0.0,10000000.0,93000000.0,21000000.0
Purchase Of Business,-114000000.0,-1108000000.0,NaN,0.0
Net PPE Purchase And Sale,-666000000.0,-545000000.0,-539000000.0,-584000000.0
Sale Of PPE,3000000.0,22000000.0,8000000.0,2000000.0
Purchase Of PPE,-669000000.0,-567000000.0,-547000000.0,-586000000.0
Operating Cash Flow,2769000000.0,7731000000.0,24881000000.0,11186000000.0
Taxes Refund Paid,-1041000000.0,-698000000.0,-1188000000.0,-635000000.0
Change In Working Capital,-6486000000.0,275000000.0,17750000000.0,3059000000.0
Change In Other Current Liabilities,NaN,-16913000000.0,16160000000.0,1349000000.0
Change In Other Current Assets,NaN,15199000000.0,-17108000000.0,-2280000000.0
Other Non Cash Items,114000000.0,106000000.0,92000000.0,105000000.0
Stock Based Compensation,134000000.0,134000000.0,131000000.0,120000000.0
Provisionand Write Offof Assets,237000000.0,52000000.0,3066000000.0,703000000.0
Depreciation And Amortization,701000000.0,669000000.0,648000000.0,609000000.0
Depreciation,701000000.0,669000000.0,648000000.0,609000000.0
Gain Loss On Investment Securities,-115000000.0,-387000000.0,-963000000.0,-334000000.0
Gain Loss On Sale Of PPE,50000000.0,13000000.0,38000000.0,26000000.0
Net Income From Continuing Operations,9382000000.0,7780000000.0,5368000000.0,7583000000.0



---

#THE END



---